Tree={branchname="Oberster Knoten",
{branchname="C:\\Tree\\Luajava_Tree",
{branchname="C:\\Tree\\Luajava_Tree\\Tree_Luajava_start.bat",
{branchname="C:\\Tree\\Luajava_Tree\\Tree_Luajava_Windows.lua",
"C:\\Tree\\Luajava_Tree\\Tree_Luajava_output.txt",
"C:\\Tree\\Luajava_Tree\\Tree_Luajava_output_Tree.lua",
},
},
},
}
