Tree=
--0: 0",
--0: 1",
{branchname="example Lua tree",
--1: 2",
{branchname="Baumdatei",
--2: 3",
{branchname="C:\\Tree\\Tree_Python\\Tree_Baum.lua",
--3: 3",
},
{branchname="Realisierung am 7.4.2022",
--3: 4",
{branchname="Dennis Würfel hat Interesse gezeigt.",
--4: 2",
},
},
},
{branchname="Output",
--2: 3",
{branchname="C:\\Tree\\Tree_Python\\Tree_Baum.lua",
--3: 2",
},
},
{branchname="Ordner 'anders'",
--2: 3",
{branchname="C:\\Tree\\Tree_Python",
--3: 4",
{branchname="C:\\Tree\\Tree_Python\\Tree_Baum_script.lua",
},
},
},
}
