C:\Temp\IDIV_Bericht.csv:

Art;Unterart;Wert;Datum
Metric1_Bud;Gesell1;1273,4;2023-1-1
Metric1_For;Gesell1;12731,4;2023-1-1
Metric1_Act;Gesell1;12723,4;2023-1-1
Metric1_Act;Gesell1;12773,4;2022-1-1
Metric2_Bud;Gesell1;1323,4;2023-1-1
Metric2_For;Gesell1;12723,4;2023-1-1
Metric2_Act;Gesell1;12713,4;2023-1-1
Metric2_Act;Gesell1;12323,4;2022-1-1
Metric1_Bud;Gesell2;12732,4;2023-1-1
Metric1_For;Gesell2;17223,4;2023-1-1
Metric1_Act;Gesell2;71233,4;2023-1-1
Metric1_Act;Gesell2;1623,4;2022-1-1
Metric2_Bud;Gesell2;123223,4;2023-1-1
Metric2_For;Gesell2;12323,4;2023-1-1
Metric2_Act;Gesell2;12423,4;2023-1-1
Metric2_Act;Gesell2;1323,4;2022-1-1
Metric1_Bud;Gesell1;1273,4;2023-2-1
Metric1_For;Gesell1;12731,4;2023-2-1
Metric1_Act;Gesell1;12723,4;2023-2-1
Metric1_Act;Gesell1;12773,4;2022-2-1
Metric2_Bud;Gesell1;1323,4;2023-2-1
Metric2_For;Gesell1;12723,4;2023-2-1
Metric2_Act;Gesell1;12713,4;2023-2-1
Metric2_Act;Gesell1;12323,4;2022-2-1
Metric1_Bud;Gesell2;12732,4;2023-2-1
Metric1_For;Gesell2;17223,4;2023-2-1
Metric1_Act;Gesell2;71233,4;2023-2-1
Metric1_Act;Gesell2;1623,4;2022-2-1
Metric2_Bud;Gesell2;123223,4;2023-2-1
Metric2_For;Gesell2;12323,4;2023-2-1
Metric2_Act;Gesell2;12423,4;2023-2-1
Metric2_Act;Gesell2;1323,4;2022-2-1
Metric1_Bud;Gesell1;1273,4;2023-3-1
Metric1_For;Gesell1;12731,4;2023-3-1
Metric1_Act;Gesell1;12723,4;2023-3-1
Metric1_Act;Gesell1;12773,4;2022-3-1
Metric2_Bud;Gesell1;1323,4;2023-3-1
Metric2_For;Gesell1;12723,4;2023-3-1
Metric2_Act;Gesell1;12713,4;2023-3-1
Metric2_Act;Gesell1;1223,4;2022-3-1
Metric1_Bud;Gesell2;12732,4;2023-3-1
Metric1_For;Gesell2;1223,4;2023-3-1
Metric1_Act;Gesell2;71233,4;2023-3-1
Metric1_Act;Gesell2;1623,4;2022-3-1
Metric2_Bud;Gesell2;23223,4;2023-3-1
Metric2_For;Gesell2;12323,4;2023-3-1
Metric2_Act;Gesell2;12423,4;2023-3-1
Metric2_Act;Gesell2;1323,4;2022-3-1
Metric1_Bud;Gesell1;173,4;2023-4-1
Metric1_For;Gesell1;12731,4;2023-4-1
Metric1_Act;Gesell1;12773,4;2022-4-1
Metric2_Bud;Gesell1;1323,4;2023-4-1
Metric2_For;Gesell1;2723,4;2023-4-1
Metric2_Act;Gesell1;12323,4;2022-4-1
Metric1_Bud;Gesell2;127932,4;2023-4-1
Metric1_For;Gesell2;1223,4;2023-4-1
Metric1_Act;Gesell2;1623,4;2022-4-1
Metric2_Bud;Gesell2;123223,4;2023-4-1
Metric2_For;Gesell2;12323,4;2023-4-1
Metric2_Act;Gesell2;1239,4;2022-4-1
Metric1_Bud;Gesell1;1273,4;2023-5-1
Metric1_For;Gesell1;12731,4;2023-5-1
Metric1_Act;Gesell1;12773,4;2022-5-1
Metric2_Bud;Gesell1;123,4;2023-5-1
Metric2_For;Gesell1;12723,4;2023-5-1
Metric2_Act;Gesell1;123923,4;2022-5-1
Metric1_Bud;Gesell2;12732,4;2023-5-1
Metric1_For;Gesell2;1223,4;2023-5-1
Metric1_Act;Gesell2;16293,4;2022-5-1
Metric2_Bud;Gesell2;123223,4;2023-5-1
Metric2_For;Gesell2;12323,4;2023-5-1
Metric2_Act;Gesell2;123,4;2022-5-1
Metric1_Bud;Gesell1;12973,4;2023-6-1
Metric1_For;Gesell1;12731,4;2023-6-1
Metric1_Act;Gesell1;12773,4;2022-6-1
Metric2_Bud;Gesell1;123,4;2023-6-1
Metric2_For;Gesell1;12723,4;2023-6-1
Metric2_Act;Gesell1;192323,4;2022-6-1
Metric1_Bud;Gesell2;12732,4;2023-6-1
Metric1_For;Gesell2;17223,4;2023-6-1
Metric1_Act;Gesell2;1623,4;2022-6-1
Metric2_Bud;Gesell2;123223,4;2023-6-1
Metric2_For;Gesell2;12323,4;2023-6-1
Metric2_Act;Gesell2;1323,4;2022-6-1
Metric1_Bud;Gesell1;1273,4;2023-7-1
Metric1_For;Gesell1;12731,4;2023-7-1
Metric1_Act;Gesell1;12773,4;2022-7-1
Metric2_Bud;Gesell1;1323,4;2023-7-1
Metric2_For;Gesell1;12723,4;2023-7-1
Metric2_Act;Gesell1;12323,4;2022-7-1
Metric1_Bud;Gesell2;12732,4;2023-7-1
Metric1_For;Gesell2;17223,4;2023-7-1
Metric1_Act;Gesell2;1623,4;2022-7-1
Metric2_Bud;Gesell2;123223,4;2023-7-1
Metric2_For;Gesell2;12323,4;2023-7-1
Metric2_Act;Gesell2;1323,4;2022-7-1
Metric1_Bud;Gesell1;1273,4;2023-8-1
Metric1_For;Gesell1;12731,4;2023-8-1
Metric1_Act;Gesell1;12773,4;2022-8-1
Metric2_Bud;Gesell1;1323,4;2023-8-1
Metric2_For;Gesell1;12723,4;2023-8-1
Metric2_Act;Gesell1;12323,4;2022-8-1
Metric1_Bud;Gesell2;12732,4;2023-8-1
Metric1_For;Gesell2;17223,4;2023-8-1
Metric1_Act;Gesell2;1623,4;2022-8-1
Metric2_Bud;Gesell2;123223,4;2023-8-1
Metric2_For;Gesell2;12323,4;2023-8-1
Metric2_Act;Gesell2;1323,4;2022-8-1
Metric1_Bud;Gesell1;1273,4;2023-9-1
Metric1_For;Gesell1;12731,4;2023-9-1
Metric1_Act;Gesell1;12773,4;2022-9-1
Metric2_Bud;Gesell1;1323,4;2023-9-1
Metric2_For;Gesell1;12723,4;2023-9-1
Metric2_Act;Gesell1;12323,4;2022-9-1
Metric1_Bud;Gesell2;12732,4;2023-9-1
Metric1_For;Gesell2;17223,4;2023-9-1
Metric1_Act;Gesell2;1623,4;2022-9-1
Metric2_Bud;Gesell2;123223,4;2023-9-1
Metric2_For;Gesell2;12323,4;2023-9-1
Metric2_Act;Gesell2;1323,4;2022-9-1
Metric1_Bud;Gesell1;1273,4;2023-10-1
Metric1_For;Gesell1;12731,4;2023-10-1
Metric1_Act;Gesell1;12773,4;2022-10-1
Metric2_Bud;Gesell1;1323,4;2023-10-1
Metric2_For;Gesell1;12723,4;2023-10-1
Metric2_Act;Gesell1;12323,4;2022-10-1
Metric1_Bud;Gesell2;12732,4;2023-10-1
Metric1_For;Gesell2;17223,4;2023-10-1
Metric1_Act;Gesell2;1623,4;2022-10-1
Metric2_Bud;Gesell2;123223,4;2023-10-1
Metric2_For;Gesell2;12323,4;2023-10-1
Metric2_Act;Gesell2;1323,4;2022-10-1
Metric1_Bud;Gesell1;1273,4;2023-11-1
Metric1_For;Gesell1;12731,4;2023-11-1
Metric1_Act;Gesell1;124773,4;2022-11-1
Metric2_Bud;Gesell1;1323,4;2023-11-1
Metric2_For;Gesell1;12723,4;2023-11-1
Metric2_Act;Gesell1;172323,4;2022-11-1
Metric1_Bud;Gesell2;12732,4;2023-11-1
Metric1_For;Gesell2;17223,4;2023-11-1
Metric1_Act;Gesell2;16236,4;2022-11-1
Metric2_Bud;Gesell2;1232923,4;2023-11-1
Metric2_For;Gesell2;12323,4;2023-11-1
Metric2_Act;Gesell2;1323,4;2022-11-1
Metric1_Bud;Gesell1;1273,4;2023-12-1
Metric1_For;Gesell1;12731,4;2023-12-1
Metric1_Act;Gesell1;124773,4;2022-12-1
Metric2_Bud;Gesell1;1323,4;2023-12-1
Metric2_For;Gesell1;12723,4;2023-12-1
Metric2_Act;Gesell1;172323,4;2022-12-1
Metric1_Bud;Gesell2;12732,4;2023-12-1
Metric1_For;Gesell2;17223,4;2023-12-1
Metric1_Act;Gesell2;16236,4;2022-12-1
Metric2_Bud;Gesell2;1232923,4;2023-12-1
Metric2_For;Gesell2;12323,4;2023-12-1
Metric2_Act;Gesell2;1323,4;2022-12-1
Metric1_Bud;Gesell1;1273,4;2022-1-1
Metric1_For;Gesell1;12731,4;2022-1-1
Metric1_Act;Gesell1;12773,4;2021-1-1
Metric2_Bud;Gesell1;1323,4;2022-1-1
Metric2_For;Gesell1;12723,4;2022-1-1
Metric2_Act;Gesell1;12323,4;2021-1-1
Metric1_Bud;Gesell2;12732,4;2022-1-1
Metric1_For;Gesell2;17223,4;2022-1-1
Metric1_Act;Gesell2;1623,4;2021-1-1
Metric2_Bud;Gesell2;123223,4;2022-1-1
Metric2_For;Gesell2;12323,4;2022-1-1
Metric2_Act;Gesell2;1323,4;2021-1-1
Metric1_Bud;Gesell1;1273,4;2022-2-1
Metric1_For;Gesell1;12731,4;2022-2-1
Metric1_Act;Gesell1;12773,4;2021-2-1
Metric2_Bud;Gesell1;1323,4;2022-2-1
Metric2_For;Gesell1;12723,4;2022-2-1
Metric2_Act;Gesell1;12323,4;2021-2-1
Metric1_Bud;Gesell2;12732,4;2022-2-1
Metric1_For;Gesell2;17223,4;2022-2-1
Metric1_Act;Gesell2;1623,4;2021-2-1
Metric2_Bud;Gesell2;123223,4;2022-2-1
Metric2_For;Gesell2;12323,4;2022-2-1
Metric2_Act;Gesell2;1323,4;2021-2-1
Metric1_Bud;Gesell1;1273,4;2022-3-1
Metric1_For;Gesell1;12731,4;2022-3-1
Metric1_Act;Gesell1;12773,4;2021-3-1
Metric2_Bud;Gesell1;1323,4;2022-3-1
Metric2_For;Gesell1;12723,4;2022-3-1
Metric2_Act;Gesell1;1223,4;2021-3-1
Metric1_Bud;Gesell2;12732,4;2022-3-1
Metric1_For;Gesell2;1223,4;2022-3-1
Metric1_Act;Gesell2;1623,4;2021-3-1
Metric2_Bud;Gesell2;23223,4;2022-3-1
Metric2_For;Gesell2;12323,4;2022-3-1
Metric2_Act;Gesell2;1323,4;2021-3-1
Metric1_Bud;Gesell1;173,4;2022-4-1
Metric1_For;Gesell1;12731,4;2022-4-1
Metric1_Act;Gesell1;12773,4;2021-4-1
Metric2_Bud;Gesell1;1323,4;2022-4-1
Metric2_For;Gesell1;2723,4;2022-4-1
Metric2_Act;Gesell1;12323,4;2021-4-1
Metric1_Bud;Gesell2;127932,4;2022-4-1
Metric1_For;Gesell2;1223,4;2022-4-1
Metric1_Act;Gesell2;1623,4;2021-4-1
Metric2_Bud;Gesell2;123223,4;2022-4-1
Metric2_For;Gesell2;12323,4;2022-4-1
Metric2_Act;Gesell2;1239,4;2021-4-1
Metric1_Bud;Gesell1;1273,4;2022-5-1
Metric1_For;Gesell1;12731,4;2022-5-1
Metric1_Act;Gesell1;12773,4;2021-5-1
Metric2_Bud;Gesell1;123,4;2022-5-1
Metric2_For;Gesell1;12723,4;2022-5-1
Metric2_Act;Gesell1;123923,4;2021-5-1
Metric1_Bud;Gesell2;12732,4;2022-5-1
Metric1_For;Gesell2;1223,4;2022-5-1
Metric1_Act;Gesell2;16293,4;2021-5-1
Metric2_Bud;Gesell2;123223,4;2022-5-1
Metric2_For;Gesell2;12323,4;2022-5-1
Metric2_Act;Gesell2;123,4;2021-5-1
Metric1_Bud;Gesell1;12973,4;2022-6-1
Metric1_For;Gesell1;12731,4;2022-6-1
Metric1_Act;Gesell1;12773,4;2021-6-1
Metric2_Bud;Gesell1;123,4;2022-6-1
Metric2_For;Gesell1;12723,4;2022-6-1
Metric2_Act;Gesell1;192323,4;2021-6-1
Metric1_Bud;Gesell2;12732,4;2022-6-1
Metric1_For;Gesell2;17223,4;2022-6-1
Metric1_Act;Gesell2;1623,4;2021-6-1
Metric2_Bud;Gesell2;123223,4;2022-6-1
Metric2_For;Gesell2;12323,4;2022-6-1
Metric2_Act;Gesell2;1323,4;2021-6-1
Metric1_Bud;Gesell1;1273,4;2022-7-1
Metric1_For;Gesell1;12731,4;2022-7-1
Metric1_Act;Gesell1;12773,4;2021-7-1
Metric2_Bud;Gesell1;1323,4;2022-7-1
Metric2_For;Gesell1;12723,4;2022-7-1
Metric2_Act;Gesell1;12323,4;2021-7-1
Metric1_Bud;Gesell2;12732,4;2022-7-1
Metric1_For;Gesell2;17223,4;2022-7-1
Metric1_Act;Gesell2;1623,4;2021-7-1
Metric2_Bud;Gesell2;123223,4;2022-7-1
Metric2_For;Gesell2;12323,4;2022-7-1
Metric2_Act;Gesell2;1323,4;2021-7-1
Metric1_Bud;Gesell1;1273,4;2022-8-1
Metric1_For;Gesell1;12731,4;2022-8-1
Metric1_Act;Gesell1;12773,4;2021-8-1
Metric2_Bud;Gesell1;1323,4;2022-8-1
Metric2_For;Gesell1;12723,4;2022-8-1
Metric2_Act;Gesell1;12323,4;2021-8-1
Metric1_Bud;Gesell2;12732,4;2022-8-1
Metric1_For;Gesell2;17223,4;2022-8-1
Metric1_Act;Gesell2;1623,4;2021-8-1
Metric2_Bud;Gesell2;123223,4;2022-8-1
Metric2_For;Gesell2;12323,4;2022-8-1
Metric2_Act;Gesell2;1323,4;2021-8-1
Metric1_Bud;Gesell1;1273,4;2022-9-1
Metric1_For;Gesell1;12731,4;2022-9-1
Metric1_Act;Gesell1;12773,4;2021-9-1
Metric2_Bud;Gesell1;1323,4;2022-9-1
Metric2_For;Gesell1;12723,4;2022-9-1
Metric2_Act;Gesell1;12323,4;2021-9-1
Metric1_Bud;Gesell2;12732,4;2022-9-1
Metric1_For;Gesell2;17223,4;2022-9-1
Metric1_Act;Gesell2;1623,4;2021-9-1
Metric2_Bud;Gesell2;123223,4;2022-9-1
Metric2_For;Gesell2;12323,4;2022-9-1
Metric2_Act;Gesell2;1323,4;2021-9-1
Metric1_Bud;Gesell1;1273,4;2022-10-1
Metric1_For;Gesell1;12731,4;2022-10-1
Metric1_Act;Gesell1;12773,4;2021-10-1
Metric2_Bud;Gesell1;1323,4;2022-10-1
Metric2_For;Gesell1;12723,4;2022-10-1
Metric2_Act;Gesell1;12323,4;2021-10-1
Metric1_Bud;Gesell2;12732,4;2022-10-1
Metric1_For;Gesell2;17223,4;2022-10-1
Metric1_Act;Gesell2;1623,4;2021-10-1
Metric2_Bud;Gesell2;123223,4;2022-10-1
Metric2_For;Gesell2;12323,4;2022-10-1
Metric2_Act;Gesell2;1323,4;2021-10-1
Metric1_Bud;Gesell1;1273,4;2022-11-1
Metric1_For;Gesell1;12731,4;2022-11-1
Metric1_Act;Gesell1;124773,4;2021-11-1
Metric2_Bud;Gesell1;1323,4;2022-11-1
Metric2_For;Gesell1;12723,4;2022-11-1
Metric2_Act;Gesell1;172323,4;2021-11-1
Metric1_Bud;Gesell2;12732,4;2022-11-1
Metric1_For;Gesell2;17223,4;2022-11-1
Metric1_Act;Gesell2;16236,4;2021-11-1
Metric2_Bud;Gesell2;1232923,4;2022-11-1
Metric2_For;Gesell2;12323,4;2022-11-1
Metric2_Act;Gesell2;1323,4;2021-11-1
Metric1_Bud;Gesell1;1273,4;2022-12-1
Metric1_For;Gesell1;12731,4;2022-12-1
Metric1_Act;Gesell1;124773,4;2021-12-1
Metric2_Bud;Gesell1;1323,4;2022-12-1
Metric2_For;Gesell1;12723,4;2022-12-1
Metric2_Act;Gesell1;172323,4;2021-12-1
Metric1_Bud;Gesell2;12732,4;2022-12-1
Metric1_For;Gesell2;17223,4;2022-12-1
Metric1_Act;Gesell2;16236,4;2021-12-1
Metric2_Bud;Gesell2;1232923,4;2022-12-1
Metric2_For;Gesell2;12323,4;2022-12-1
Metric2_Act;Gesell2;1323,4;2021-12-1

shared IDIV_Bericht = let
    Quelle = Csv.Document(File.Contents("C:\Temp\IDIV_Bericht.csv"),[Delimiter=";", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Art", type text}, {"Unterart", type text}, {"Wert", type number}, {"Datum", type date}}),
    #"Hinzugefügte benutzerdefinierte Spalte" = Table.AddColumn(#"Geänderter Typ", "Artgruppe", each Text.Replace(Text.Replace(Text.Replace([Art],"_Bud",""),"_For",""),"_Act","")),
    #"Hinzugefügte benutzerdefinierte Spalte1" = Table.AddColumn(#"Hinzugefügte benutzerdefinierte Spalte", "Art_Ansicht_Jahr", each if Date.IsInPreviousYear([Datum]) and Text.Contains([Art],"_Act") then "Previous Year" else if Date.IsInCurrentYear([Datum]) and Text.Contains([Art],"_Act") then "Actual" else if Date.IsInCurrentYear([Datum]) and Text.Contains([Art],"_Bud") then "Budget" else if Date.IsInCurrentYear([Datum]) and Text.Contains([Art],"_For") then "Forecast" else "Not in Report"),
    #"Hinzugefügte benutzerdefinierte Spalte2" = Table.AddColumn(#"Hinzugefügte benutzerdefinierte Spalte1", "Art_Ansicht_Kategorie", 	
    each if [Unterart] = "Gesell1" then "GmbH"
	else [Unterart])
in
    #"Hinzugefügte benutzerdefinierte Spalte2";
