tree_from_csv={branchname="Baum erstellt am: Thu Oct 21 20:08:36 2021",{branchname="Employees",{branchname="Abfrage11",{branchname="ORDER_BY T1.Title",},
{branchname="WHERE T1.Title = Employees.Title)))",},
{branchname="SUB_SELECT Avg(Salary)",},
{branchname="WHERE (((T1.[Salary])>=",},
{branchname="SELECT T1.LastName, T1.FirstName, T1.Title, T1.Salary",},
},
},
{branchname="Employees AS T1",{branchname="Abfrage11",{branchname="ORDER_BY T1.Title",},
{branchname="WHERE T1.Title = Employees.Title)))",},
{branchname="SUB_SELECT Avg(Salary)",},
{branchname="WHERE (((T1.[Salary])>=",},
{branchname="SELECT T1.LastName, T1.FirstName, T1.Title, T1.Salary",},
},
},
{branchname="OrderDetails",{branchname="Abfrage10",{branchname="SUB_SELECT ProductID",},
{branchname="WHERE ProductID IN",},
{branchname="SELECT *",},
{branchname="WHERE Discount >= .25)",},
},
},
{branchname="Products",{branchname="Form: Products",},
{branchname="Report: Products",},
{branchname="Abfrage10",{branchname="SUB_SELECT ProductID",},
{branchname="WHERE ProductID IN",},
{branchname="SELECT *",},
{branchname="WHERE Discount >= .25)",},
},
{branchname="~sq_rProducts",{branchname="SELECT DISTINCTROW *",},
},
{branchname="~sq_fProducts",{branchname="SELECT DISTINCTROW *",},
},
},
{branchname="Tabelle1",{branchname="Abfrage2_1",{branchname="Form: Abfrage2_1",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
{branchname="SELECT Tabelle1.Feld1, Tabelle2.Feld2",},
},
{branchname="Abfrage1",{branchname="Form: Formular1",},
{branchname="Abfrage4",{branchname="SELECT Abfrage1.Feld1",},
{branchname="INSERT_FIELD( Tabelle1_Feld1 )",},
{branchname="Testdaten",{branchname="Abfrage6",{branchname="SELECT Testdaten.Abfrage2_Feld1",},
{branchname="TRANSFORM Count(Testdaten.Feld2) AS AnzahlvonFeld2",},
{branchname="GROUP_BY Testdaten.Abfrage2_Feld1",},
{branchname="PIVOT Testdaten.Tabelle1_Feld1",},
},
},
},
{branchname="SELECT Tabelle1.Feld1",},
{branchname="Report: Abfrage1",},
},
{branchname="Abfrage2_2",{branchname="SELECT Tabelle1.Feld1, Tabelle2.Feld2",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
},
{branchname="Abfrage8",{branchname="Abfrage9",{branchname="SELECT Abfrage8.Feld1",},
},
{branchname="SELECT Tabelle2.Feld1",},
{branchname="SELECT Tabelle1.Feld1",},
{branchname="UNION",},
},
{branchname="Abfrage3",{branchname="Testdaten",{branchname="Abfrage6",{branchname="SELECT Testdaten.Abfrage2_Feld1",},
{branchname="TRANSFORM Count(Testdaten.Feld2) AS AnzahlvonFeld2",},
{branchname="GROUP_BY Testdaten.Abfrage2_Feld1",},
{branchname="PIVOT Testdaten.Tabelle1_Feld1",},
},
},
{branchname="SELECT Tabelle1.Feld1, Abfrage2.Feld2, Abfrage2.Feld1",},
{branchname="ON Tabelle1.Feld1 = Abfrage2.Feld2",},
},
{branchname="Duplikate suchen für Tabelle1",{branchname="SELECT First(Tabelle1.Feld1) AS [Feld1 Feld], Count(Tabelle1.Feld1) AS AnzahlVonDuplikaten",},
{branchname="GROUP_BY Tabelle1.Feld1",},
{branchname="HAVING (((Count(Tabelle1.Feld1))>1))",},
},
{branchname="Abfrage2",{branchname="Abfrage3",{branchname="Testdaten",{branchname="Abfrage6",{branchname="SELECT Testdaten.Abfrage2_Feld1",},
{branchname="TRANSFORM Count(Testdaten.Feld2) AS AnzahlvonFeld2",},
{branchname="GROUP_BY Testdaten.Abfrage2_Feld1",},
{branchname="PIVOT Testdaten.Tabelle1_Feld1",},
},
},
{branchname="SELECT Tabelle1.Feld1, Abfrage2.Feld2, Abfrage2.Feld1",},
{branchname="ON Tabelle1.Feld1 = Abfrage2.Feld2",},
},
{branchname="SELECT Tabelle1.Feld1, Tabelle2.Feld2",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
},
{branchname="Abfrage5",{branchname="SET Tabelle1.Feld1 = 'Test'",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
{branchname="WHERE (((Tabelle2.Feld1)>0))",},
},
},
{branchname="Tabelle2",{branchname="Abfrage2",{branchname="Abfrage3",{branchname="Testdaten",{branchname="Abfrage6",{branchname="SELECT Testdaten.Abfrage2_Feld1",},
{branchname="TRANSFORM Count(Testdaten.Feld2) AS AnzahlvonFeld2",},
{branchname="GROUP_BY Testdaten.Abfrage2_Feld1",},
{branchname="PIVOT Testdaten.Tabelle1_Feld1",},
},
},
{branchname="SELECT Tabelle1.Feld1, Abfrage2.Feld2, Abfrage2.Feld1",},
{branchname="ON Tabelle1.Feld1 = Abfrage2.Feld2",},
},
{branchname="SELECT Tabelle1.Feld1, Tabelle2.Feld2",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
},
{branchname="Abfrage2_2",{branchname="SELECT Tabelle1.Feld1, Tabelle2.Feld2",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
},
{branchname="Abfrage7",{branchname="DELETE Tabelle2.Feld1",},
{branchname="WHERE (((Tabelle2.Feld1)>'Z'))",},
},
{branchname="Abfrage8",{branchname="Abfrage9",{branchname="SELECT Abfrage8.Feld1",},
},
{branchname="SELECT Tabelle2.Feld1",},
{branchname="SELECT Tabelle1.Feld1",},
{branchname="UNION",},
},
{branchname="Abfrage2_1",{branchname="Form: Abfrage2_1",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
{branchname="SELECT Tabelle1.Feld1, Tabelle2.Feld2",},
},
{branchname="Abfrage5",{branchname="SET Tabelle1.Feld1 = 'Test'",},
{branchname="ON Tabelle1.Feld1 = Tabelle2.Feld2",},
{branchname="WHERE (((Tabelle2.Feld1)>0))",},
},
},
}
