= Examples/Beispiele/exemples

== Introduction
This repository contains examples of interactive dynamic tables of contents.

Dieser Ordner enthält Beispieldateien von interaktiv-dynamischen Inhaltsverzeichnissen.

Ce répertoire contiens des exemples de tables des matières interactive dynamiques.

== 1. arborescence avec des comptes

=== 1.1 IDIV_analyse_bilan.lua

This script contains the IDIV-Bilanzanalysewerkzeug (IDIV-outil d'analyse du bilan).

=== 1.2 IDIV_analyse_comptes.lua

This script contains a tool to show a list of assets and the tree of clients having these assets.

== 2. arboresences simples

=== 2.1 IDIV_arborescence_simple.lua

This script contains the IDIV-Basiskomponente (IDIV-arborescence simple).

=== 2.2 IDIV_arborescence_simple_avec_choix_fichier.lua

This script contains the IDIV-Basiskomponente mit Dateiauswahl (IDIV-arborescence avec choix de fichier).

==== 2.2.1 Tree_Baum.lua

This is an example file for a tree.

=== 2.3 IDIV_arborescence_simple_navigation_web.lua

This script contains the IDIV-Basiskomponente mit Browserfunktion (IDIV-arborescence avec navigation web).

=== 2.4 IDIV_arborescence_simple_reflexive.lua

This script contains the IDIV-Basiskomponente in einer Datei (IDIV-arborescence simple reflexive).

== 3. outils de base
=== 3.1 IDIV_bibliotheque.lua

This script contains the IDIV-Bibliothek (IDIV-bibliothèque).

=== 3.2 IDIV_bureau.lua

This script contains the IDIV-Arbeitsplatz (IDIV-bureau).

== 4. calculs

=== 4.1 IDIV_calcul_interests_reflexif.lua

This script contains the IDIV-Entwicklungsumgebung für Kalkulationsschemata (IDIV-outil de dévelopement de schémas de calculs).

=== 4.2 IDIV_calcul_interets.lua

This script contains the IDIV-Zinskalkulationsschema mit Standardquellen (IDIV-calcul des intérêts).

== 5. IDIV_capture_ecran.lua

This script contains the IDIV-Bildschirmausdruck (IDIV-capture écran).

== 6. IDIV_categorisation_nouvelles.lua

This script contains the IDIV-Nachrichtenverarbeitung (IDIV-catégorisation de nouvelles).

== 7. outils de comparaison

=== 7.1 IDIV_comparaison_arbres.lua

This script contains the IDIV-Baumansichtvergleich (IDIV-comparaison d'arbres).

=== 7.2 IDIV_comparaison_textes.lua

This script contains the IDIV-Textdateivergleich (IDIV-comparaison de textes).

== 8. IDIV_console.lua

This script contians the IDIV-Skripter (IDIV-console).

== 9. IDIV_conversion.lua

This script contains the IDIV-Konvertierung (IDIV-conversion).

== 10. outils de traitement de données entrée et sortie

=== 10.1 IDIV_entree_traitement_sortie.lua

This script contains the IDIV-Analysewerkzeug (IDIV-outil d'analyse).

=== 10.2 IDIV_entree_traitement_sortie_MDI_graphiques.lua

This script contains the IDIV-Analysewerkzeug mit Darstellung (IDIV-outil d'analyse avec représentation).

== 11. IDIV_images_reflexives.lua

This script contains the IDIV-Graphiken-Anzeige (IDIV-images).

== 12. IDIV_livre_reflexif.lua

This script contains the IDIV-Textheft (IDIV-livre).

== 13. IDIV_navigation_web_reflexive.lua

This script contains the IDIV-Browser (IDIV-navigation web).

== 14. presentations
=== 14.1 IDIV_presentation_reflexive.lua

This script contains the IDIV-Präsentation (IDIV-présentation).

=== 14.2 IDIV_presentation_video.lua

This script contains the IDIV-Video-Präsentation (IDIV-présentation vidéo).

== 15. IDIV_recherche_internet_reflexive.lua

This script contains the IDIV-Suchergebnisse Internet (IDIC-recherche internet).

== 16. IDIV_repertoire.lua

This script contains the IDIV-Ordnergliederung (IDIV-répertoire).

== 17. IDIV_syntax_de_Lua_reflexive.lua

This script contains IDIV-Browser der Lua-Syntax (IDIV-Syntaxe de Lua).

== 18. IDIV_traitement_texte_reflexif.lua

This script contains the IDIV-Textverarbeitung (IDIV-traitement de textes).


