= Examples/Beispiele/exemples

== Introduction
This repository contains examples of interactive dynamic tables of contents. 

Dieser Ordner enthält Beispieldateien von interaktiv-dynamischen Inhaltsverzeichnissen.

Ce répertoire contiens des exemples de tables des matières interactive dynamiques.

== 1. arborescences sur papier

Trees can also be written by hand on paper. As a standard the root ist written in a box. The lines between nodes are drawn as L. The highest level under the root can be underlinned. If necessary levels can be underlined another time so that the highest level under the root is underlined twice and the second level once and so on.

Baumansichten können auch auf Papier geschrieben werden. Als Standard wird der oberste Knoten, der Stamm, in einer Box geschrieben. Die Linien zum Verbinden der Knoten werden als L geschrieben. Die höchste Ebene unter dem Stamm kann einfach unterstrichen werden. Bei Bedarf können die Ebenen erneut unterstrichen werden, so dass die höchste Ebene zweimal und die zweite Ebene einmal unterstrichen sind usw.

Les arborescences peuvent aussi être écrite sur papier. La convention est d'écrire le tronc dans un rectangle. Les lignes entre les branches et les feuilles sont dessinées en form de L. Le niveau le plus élevé en dessous du tronc peut être souligné. Si néecessaire les niveaux sont soulignés une fois de plus de tel manière que le niveau le plus élevé en dessous du tronc est souligné deux fois, le second niveau est souligné une fois etc.

== 1.1 IDIV-Papier_1.png

This photo shows a IDIV-papier with highest level under root underlined one time.

== 1.2 IDIV-Papier_2.png

This photo shows a IDIV-papier with highest level under root underlined two time and the second level underlined twice.

== 2. arborescence avec des comptes

=== 2.1 IDIV_analyse_bilan.lua

This script contains the IDIV-Bilanzanalysewerkzeug (IDIV-outil d'analyse du bilan).

=== 2.2 IDIV_analyse_comptes.lua

This script contains a tool to show a list of assets and the tree of clients having these assets.

== 3. arboresences simples

=== 3.1 IDIV_arborescence_simple.lua

This script contains the IDIV-Basiskomponente (IDIV-arborescence simple).

=== 3.2 IDIV_arborescence_simple_avec_choix_fichier.lua

This script contains the IDIV-Basiskomponente mit Dateiauswahl (IDIV-arborescence avec choix de fichier).

==== 3.2.1 Tree_Baum.lua

This is an example file for a tree.

=== 3.3 IDIV_arborescence_simple_navigation_web.lua

This script contains the IDIV-Basiskomponente mit Browserfunktion (IDIV-arborescence avec navigation web).

=== 3.4 IDIV_arborescence_simple_reflexive.lua

This script contains the IDIV-Basiskomponente in einer Datei (IDIV-arborescence simple reflexive).

== 4. outils de base
=== 4.1 IDIV_bibliotheque.lua

This script contains the IDIV-Bibliothek (IDIV-bibliothèque).

=== 4.2 IDIV_bureau.lua

This script contains the IDIV-Arbeitsplatz (IDIV-bureau).

=== 4.2.1 IDIV_bureau_simplifie.lua

This script contains a simplified version of the IDIV-Arbeitsplatz (IDIV-bureau simplifié).

== 5. calculs

=== 5.1 IDIV_calcul_interests_reflexif.lua

This script contains the IDIV-Entwicklungsumgebung für Kalkulationsschemata (IDIV-outil de dévelopement de schémas de calculs).

=== 5.2 IDIV_calcul_interets.lua

This script contains the IDIV-Zinskalkulationsschema mit Standardquellen (IDIV-calcul des intérêts).

== 6. IDIV_capture_ecran.lua

This script contains the IDIV-Bildschirmausdruck (IDIV-capture écran).

== 7. IDIV_categorisation_nouvelles.lua

This script contains the IDIV-Nachrichtenverarbeitung (IDIV-catégorisation de nouvelles).

== 8. outils de comparaison

=== 8.1 IDIV_comparaison_arbres.lua

This script contains the IDIV-Baumansichtvergleich (IDIV-comparaison d'arbres).

=== 8.2 IDIV_comparaison_textes.lua

This script contains the IDIV-Textdateivergleich (IDIV-comparaison de textes).

== 9. IDIV_console.lua

This script contians the IDIV-Skripter (IDIV-console).

== 10. IDIV_conversion.lua

This script contains the IDIV-Konvertierung (IDIV-conversion).

== 11. outils de traitement de données entrée et sortie

=== 11.1 IDIV_entree_traitement_sortie.lua

This script contains the IDIV-Analysewerkzeug (IDIV-outil d'analyse).

=== 11.2 IDIV_entree_traitement_sortie_MDI_graphiques.lua

This script contains the IDIV-Analysewerkzeug mit Darstellung (IDIV-outil d'analyse avec représentation).

== 12. IDIV_images_reflexives.lua

This script contains the IDIV-Graphiken-Anzeige (IDIV-images).

== 13. IDIV_livre_reflexif.lua

This script contains the IDIV-Textheft (IDIV-livre).

== 14. IDIV_navigation_web_reflexive.lua

This script contains the IDIV-Browser (IDIV-navigation web).

== 15. presentations
=== 15.1 IDIV_presentation_reflexive.lua

This script contains the IDIV-Präsentation (IDIV-présentation).

=== 15.2 IDIV_presentation_video.lua

This script contains the IDIV-Video-Präsentation (IDIV-présentation vidéo).

== 16. IDIV_recherche_internet_reflexive.lua

This script contains the IDIV-Suchergebnisse Internet (IDIC-recherche internet).

== 17. IDIV_repertoire.lua

This script contains the IDIV-Ordnergliederung (IDIV-répertoire).

== 18. IDIV_syntax_de_Lua_reflexive.lua

This script contains IDIV-Browser der Lua-Syntax (IDIV-Syntaxe de Lua).

== 19. IDIV_traitement_texte_reflexif.lua

This script contains the IDIV-Textverarbeitung (IDIV-traitement de textes).


