lua_tree_output={ branchname="output", 
{ branchname="C:\\Tree\\LuatoLua\\input_command_output_tree_internal_interest_rate_output.lua", 
state="COLLAPSED",
},
{ branchname="Ergebnis Summe der Zinsen über die gesamte Laufzeit", 
{ branchname="4 Jahre", 
 "206", 
},
{ branchname="16 Jahre", 
 "7509", 
},
},
{ branchname="Schätzergebnisse auf die Laufzeit als Differenz aus abgezinsten Ein- und Auszahlungen", 
{ branchname="Schätzergebnisse auf 4 Jahre", 
 "0.00092715430218959", 
},
{ branchname="Schätzergebnisse auf 16 Jahre", 
 "0.025344457688334", 
}}}