lua_tree_command={ branchname="command", 
{ branchname="C:\\Tree\\LuatoLua\\input_command_output_tree_command.lua", 
state="COLLAPSED",
},
{ branchname="historische Ergebnisse", 
{ branchname="for i=15,#a do b[i]=b[i-1]+a[i] end", 
{ branchname="for i,v in ipairs(a) do print(os.date(\"%d.%m.%Y\",os.time{year=2021,month=11,day=8+i}) .. \": \" .. tostring(b[i]) .. \": \" .. v) end", 
{ branchname="schaetzAnfang=#a+1 --print(schaetzAnfang)", 
state="COLLAPSED",
},
},
},
},
{ branchname="Schätzergebnisse", 
{ branchname="for i=schaetzAnfang,1042 do a[i]=a[i-7]/a[i-14]*a[i-7] b[i]=b[i-1]+a[i] print(i .. \": \" .. os.date(\"%d.%m.%Y\",os.time{year=2021,month=11,day=8+i}) .. \": \" .. math.floor((i-1)/7)+1 .. \": \" .. b[i]) end ", 
state="COLLAPSED",
}}}