lua_tree_command={ branchname="command", 
{ branchname="C:\\Tree\\LuatoLua\\input_command_output_tree_internal_interest_rate_command.lua", 
state="COLLAPSED",
},
{ branchname="historische Ergebnisse", 
{ branchname="Gesamtzahlung=0 for i=0,#a do Gesamtzahlung=Gesamtzahlung+a[i] end print(-Gesamtzahlung)", 
state="COLLAPSED",
},
},
{ branchname="Schätzergebnisse auf 4 Jahre", 
{ branchname="r=0.00216656/12 b={} for i=#a,0,-1 do b[i]=a[i]/(1+r)^i end", 
{ branchname="Gesamtsumme=0 for i=0,#b do Gesamtsumme=Gesamtsumme+b[i] end print(Gesamtsumme)", 
state="COLLAPSED",
},
},
},
{ branchname="Schätzergebnisse auf 16 Jahre", 
{ branchname="r=0.0124796/12 b={} for i=#a,0,-1 do b[i]=a[i]/(1+r)^i end", 
{ branchname="Gesamtsumme=0 for i=0,#b do Gesamtsumme=Gesamtsumme+b[i] end print(Gesamtsumme)", 
state="COLLAPSED",
}}}}