lua_tree_output={ branchname="console", 
 "Lua 5.4", 
 "IUP 3.30  Copyright (C) 1994-2020 Tecgraf/PUC-Rio", 
 "  System: Win8", 
 "  System Version: 6.2.9200 (x64)", 

{ branchname="print(_VERSION)", 
state="COLLAPSED",
 "Lua 5.4", 
},
{ branchname="Word mit LuaCOM", 
{ branchname="require(\"luacom\") word=luacom.CreateObject(\"Word.Application\") word.Visible=true", 
{ branchname="word.Documents:Add()", 
state="COLLAPSED",
},
{ branchname="word.Documents:Open(\"C:\\\\Users\\\\RK\\\\Documents\\\\Bruno\\\\testdatei.docx\")", 
state="COLLAPSED",
},
{ branchname="print(luacom.DumpTypeInfo(word))", 
state="COLLAPSED",
 "nil", 
},
},
},
{ branchname="Excel mit LuaCOM", 
{ branchname="require(\"luacom\") excel=luacom.CreateObject(\"Excel.Application\") excel.Visible=true", 
{ branchname="excel.Workbooks:Add()", 
state="COLLAPSED",
},
},
},
{ branchname="Powerpoint mit LuaCOM", 
{ branchname="require(\"luacom\") powerpoint=luacom.CreateObject(\"Powerpoint.Application\") powerpoint.Visible=true", 
{ branchname="powerpoint.Presentations:Add() ", 
state="COLLAPSED",
},
},
},
{ branchname="Access mit LuaCOM", 
{ branchname="require(\"luacom\") access=luacom.CreateObject(\"Access.Application\") access.Visible=true access:OpenCurrentDatabase(\"C:\\\\Temp\\\\Daten.accdb\")", 
{ branchname="rs1=access:CurrentDB().QueryDefs ", 
state="COLLAPSED",
},
{ branchname="rs2=access.Application.CurrentProject.AllForms ", 
state="COLLAPSED",
},
{ branchname="rs3=access.Application.CurrentProject.AllReports ", 
state="COLLAPSED",
},
{ branchname="rs4=access:CurrentDB().TableDefs ", 
state="COLLAPSED",
},
},
{ branchname="access:Quit() os.execute(\'taskkill /IM MSACCESS.EXE /F\') ", 
state="COLLAPSED",
},
},
{ branchname="Lua-Skript ausführen", 
{ branchname="C:\\Temp\\test.lua", 
state="COLLAPSED",
 "Das ist ein Test", 
 "Und ein anderer Test", 
 "Und ein 3. Test", 
 "Und ein 4. Test", 
},
{ branchname="dofile(\"C:\\\\Temp\\\\test.lua\")", 
state="COLLAPSED",
 "Das ist ein Test", 
 "Und ein anderer Test", 
 "Und ein 3. Test", 
 "Und ein 4. Test", 
}}}